# Copyright

<PRE>
This notebook was created as part of the "Deep learning / VITMMA19" class at
Budapest University of Technology and Economics, Hungary,
https://portal.vik.bme.hu/kepzes/targyak/VITMMA19
Based on the official documentation:
https://numpy.org/doc/stable/user/quickstart.html

Any re-use or publication of any part of the notebook is only allowed with the
 written consent of the authors.

2023 (c) Tamás Gábor Csapó, Márk Császár,  Bálint Gyires-Tóth (toth.b kukac tmit pont bme pont hu)
</PRE>

# Numpy package

One of the most commonly used Python packages for machine learning and thus deep learning is Numpy, which can be loaded with the following command and referred to later as np.

In [2]:
import numpy as np

Numpy is basically used to handle homogeneous, one- or multidimensional matrices (= arrays = tensors). The elements of these matrices are numbers of the same type, and their position within the array can be specified by positive integers.

# Numpy arrays - properties


Important, frequently used features:

    ndarray.ndim - Dimension of the array.

    ndarray.shape - The shape of the array, which gives the size of the array along each dimension. For 2 dimensional matrices, n rows and m columns will be a matrix shape (n,m).

    ndarray.size - The number of elements in the array, equal to the product of the dimensions along each dimension.

    ndarray.dtype - The type of elements in the array.

Other notable features (we will rarely use these):

    ndarray.itemsize - The size of each item, expressed in bytes, in accordance with the previously mentioned type.

    ndarray.data - Buffer containing all the items in the array.


# Numpy arrays - how to create

Data types relevant for deep learning systems:

    bool_ (e.g. binary data)
    
    int_ (e.g. RGB channels of images)
    
    float_ (32 bits, general data)
    
    float16_ (16-bit, half-precision, general data): gaining more and more space because of its advantages (faster, more memory efficient and good for deep learning)

Wrong solution:

In [3]:
a = np.array(1,2,3,4)    # WRONG


TypeError: ignored

Right solution:

In [4]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

Create a 2-dimensional Numpy array:




In [5]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

When declaring an array, you can also specify the type of the elements (and thus the array):

In [6]:
c = np.array( [ [1.2,2.3], [3.7,4.5] ], dtype=float )
c

array([[1.2, 2.3],
       [3.7, 4.5]])

Create a 3x4 array of all zeros, using the numpy.zeros() function (often used):

In [7]:
d = np.zeros( (3,4) )
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create 2 arrays of size 3x4 (i.e. a 3D array) with numpy.ones() containing all ones (16-bit integers):

In [8]:
e = np.ones( (2,3,4), dtype=np.int16 )
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Create a 2x3 empty array using numpy.empty(). Numpy then assigns memory addresses to the elements of the array, which will be set to the values contained in the memory addresses.

In [9]:
f = np.empty( (2,3) )
f

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

linspace: from the interval bounded by the first and second argument, the third argument places a number of elements equidistant from each other and writes them into a numpy array (often used).

In [10]:
g = np.linspace( 0, 2, 9 )  # generates 9 numbers between 0 and 2
g

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

The same function from -2pi and 2pi with 15 elements:

In [11]:
h = np.linspace( -2*np.pi, 2*np.pi , 15 )
h

array([-6.28318531, -5.38558741, -4.48798951, -3.5903916 , -2.6927937 ,
       -1.7951958 , -0.8975979 ,  0.        ,  0.8975979 ,  1.7951958 ,
        2.6927937 ,  3.5903916 ,  4.48798951,  5.38558741,  6.28318531])

Similar to linspace(), but it is best used when the scaling measure is an integer. If you do not specify a range boundary or scale as a parameter, you can simply create a new array which will be automatically populated.

In [12]:
i = np.arange(15)
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

If too many array elements should be displayed, only the last elements of the ranges are visualised.

In [13]:
print(np.eye(100))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


# Basic operations

create an "a" array:

In [14]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

creating a "b" array

In [15]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

Element-by-element subtraction:

In [16]:
c = a-b
c

array([20, 29, 38, 47])

the square of the elements of array "b":

In [17]:
b**2

array([0, 1, 4, 9])

Calculate the 10*sine values of the elements of the array. In the case of Numpy functions, it is sufficient to pass only the array itself to the function. There is no need to iterate over all the elements.

In [19]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

Check the condition and create a "boolean" array from the original array:

In [20]:
a<35

array([ True,  True, False, False])

Create "A" 2x2 array with predefined value:

In [21]:
A = np.array( [[1,1],
              [0,1]] )

Create "B" 2x2 array:

In [23]:
B = np.array( [[2,0],
              [3,4]] )

Element-wise multiplication of A and B:


In [24]:
A*B

array([[2, 0],
       [0, 4]])

Matrix multiplication of A and B using numpy.dot(). (both lines do the same thing)
.

In [25]:
np.dot(A, B)
A.dot(B)

array([[5, 4],
       [3, 4]])

Create an array "a" of ones and multiply each element of "a" by 3:

In [26]:
a = np.ones((2,3), dtype=int)
a
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

Create and fill a 2x3 matrix from the range [0.0, 1.0) randomly. (The two approaches do the same thing.)

In [29]:
b = np.random.random((2,3))
b

array([[0.05532767, 0.95266721, 0.00450346],
       [0.4318087 , 0.83570745, 0.16158628]])

In [30]:
b = np.random.rand(2,3)
b

array([[0.84412321, 0.92816326, 0.03354348],
       [0.98354443, 0.01605153, 0.90275159]])

You can also add the elements of array a to the elements of array b:

In [31]:
b += a
b

array([[3.84412321, 3.92816326, 3.03354348],
       [3.98354443, 3.01605153, 3.90275159]])

# Random seed

If you specify a random seed, then every time you restart your script, it will generate the same random numbers one after the other. This helps us to work with the same random numbers every time we run it, so that different results are not generated from different random numbers.

In [32]:
np.random.seed(42)
print(np.random.rand(2,3))
print(np.random.rand(2,3))
print(np.random.rand(2,3))
print(np.random.rand(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]
[[0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]


In [33]:
np.random.seed(42)
print(np.random.rand(2,3))
print(np.random.rand(2,3))
print(np.random.rand(2,3))
print(np.random.rand(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]
[[0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]


# Unary operators

Create and fill a 3x4 array with numpy.arange():

In [34]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Calculation of column and row sums:

In [35]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [36]:
b.sum(axis=1)

array([ 6, 22, 38])

The smallest elements per column and per row within the array:

In [37]:
b.min(axis=0)

array([0, 1, 2, 3])

In [38]:
b.min(axis=1)

array([0, 4, 8])

Cumulative sums per column and per row:

In [39]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [40]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

If no *axis* parameter is specified, it performs the operation on the whole array:

In [41]:
b.sum()

66

In [42]:
b.min()

0

In [43]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

# Indexing


Cube of first 10 non-negative integers:

In [44]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

The numbering of the arrays starts from 0.

In [45]:
a[2]

8

Select an interval within an array. The upper limit of the interval is not included in the selection.

In [46]:
a[2:5]

array([ 8, 27, 64])

From the first element to the sixth, we give every second element a value of 1000:

In [47]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

Invert row vector:

In [48]:
a[ : :-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

5x4-es matrix:

In [49]:
b = np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Both column and row indexes start from 0:

In [50]:
b[2,3]

11

The first five elements of the second column:



In [ ]:
b[0:5, 1]

array([ 1,  5,  9, 13, 17])

last row of array "b":

In [51]:
b[-1]

array([16, 17, 18, 19])

# Manipulating the shape of the Numpy array

3x4-es matrix with random numbers:

In [52]:
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 7., 1., 5.],
       [5., 0., 6., 1.],
       [0., 9., 9., 8.]])

Transform the original 3x4 matrix into a row vector with numpy.reshape():

In [53]:
a.reshape(1,12)

array([[4., 7., 1., 5., 5., 0., 6., 1., 0., 9., 9., 8.]])

You can also use numpy.shape() if the number of elements is not changed by the transformation:

In [54]:
a.shape = (6, 2)
a

array([[4., 7.],
       [1., 5.],
       [5., 0.],
       [6., 1.],
       [0., 9.],
       [9., 8.]])

The transpose of the matrix. It can be used only in case of 1 and 2 dimensions:

In [55]:
a.T

array([[4., 1., 5., 6., 0., 9.],
       [7., 5., 0., 1., 9., 8.]])

You can specify how many rows you want to see and the number of columns will be calculated automatically:

In [56]:
a.reshape(3,-1)

array([[4., 7., 1., 5.],
       [5., 0., 6., 1.],
       [0., 9., 9., 8.]])

# Concatenating matrices

Create 2 arrays of 2x2 with random elements. Numpy.floor() converts to the lower integer:

In [57]:
a = np.floor(10*np.random.random((2,2)))
a

array([[3., 0.],
       [6., 4.]])

In [58]:
b = np.floor(10*np.random.random((2,2)))
b

array([[1., 4.],
       [0., 9.]])

Concatenate the two arrays along dimension 1 (vertical) and dimension 2 (horizontal):

In [59]:
np.concatenate((a, b), axis=0 )

array([[3., 0.],
       [6., 4.],
       [1., 4.],
       [0., 9.]])

In [60]:
np.concatenate((a, b), axis=1 )

array([[3., 0., 1., 4.],
       [6., 4., 0., 9.]])

# Copying matrices

Create a row vector of the first 12 non-negative numbers:

In [61]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

"b" array will be equal to "a":

In [64]:
b = a

Check whether they are equal:

In [65]:
b is a

True

If I change the shape of b, then the shape of a also changes:

In [66]:
b.shape = 3,4
a.shape

(3, 4)

Let "c" be an array that looks the same as "a":

In [67]:
c = a.view()
c is a

False

Through array "c" we see the elements of array "a":

In [68]:
c.base is a

True

If I change the shape of "c", then the shape of "a" does not change:

In [69]:
c.shape = 2,6
a.shape

(3, 4)

If I change the fourth element of array "c":

In [70]:
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Making a deep copy of the array. The "d" array does not refer to "a" but is independent of it:

In [71]:
d = a.copy()
d is a

False

In [72]:
d.base is a

False

# Garbage collector

The Python programming language has garbage collection to avoid memory leaks. In deep neural networks, we work with large amounts of data, so in many cases it may be necessary to "manually" flush memory before scheduling Python. This can be done as follows:

In [73]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 6., 3., 5.],
       [5., 1., 9., 7.],
       [9., 8., 5., 9.]])

In [74]:
a = []
a

[]

Import the Garbage Collector (GC) module and collect the entire memory garbage. The return value of gc.collect() is the number of items not reached.

In [75]:
import gc
gc.collect()

56